# Generated by Django 3.2.16 on 2023-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
