# Generated by Django 3.2.16 on 2023-01-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcsion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
